# Generated by Django 5.1.2 on 2024-10-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_tags_project_vote_ratio_project_vote_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
