# Generated by Django 5.1.2 on 2024-10-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200, null=True),
        ),
    ]
